add_newline = false
scan_timeout = 10

[aws]
symbol = "aws "

[azure]
symbol = "az "

[battery]
disabled = true

[bun]
symbol = "bun "

[c]
symbol = "C "

[character]
error_symbol = "[\\$](bold red)"
success_symbol = "[\\$](bold green)"
vimcmd_symbol = "[\\[VISUAL\\]](bold yellow) [\\$](bold green)"

[cmake]
symbol = "cmake "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[daml]
symbol = "daml "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[directory]
read_only = " ro"

[docker_context]
symbol = "docker "

[dotnet]
symbol = ".NET "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[fennel]
symbol = "fnl "

[fossil_branch]
symbol = "fossil "

[gcloud]
symbol = "gcp "

[git_branch]
symbol = "git "

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
deleted = "x"
diverged = "<>"
renamed = "r"

[golang]
symbol = "go "

[gradle]
symbol = "gradle "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[jobs]
number_threshold = 4
symbol = "+ "
symbol_threshold = 1

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[lua]
symbol = "lua "

[memory_usage]
symbol = "memory "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[nodejs]
symbol = "nodejs "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
Alpaquita = "alq "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
RedHatEnterprise = "rhel "
Redhat = "rhl "
Redox = "redox "
SUSE = "suse "
Solus = "sol "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "
openEuler = "oeul "
openSUSE = "osuse "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pijul_channel]
symbol = "pijul "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[raku]
symbol = "raku "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[solidity]
symbol = "solidity "

[spack]
symbol = "spack "

[status]
symbol = "[:(](bold red) "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
